apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: crossplane
    includeCRDs: true
    releaseName: crossplane
    version: 1.9.1
    repo: https://charts.crossplane.io/stable
